### ISSUE TITLE
Question about why transpose Weight Matrix when load "NSP" layer (THX)

### ISSUE THREAD

**Issue by Zenghao-CQ** [CyberZHG/keras-bert#137]
Thanks for your working, its both solid and elegant!
But i am so confused that why you **transpose** the weight matrix when loading **"NSP"** layer (at line 142 in loader.py)?  MLM_Dense, NSP_Dense and NSP are all Dense layers, but why only transpose weight NSP?
THX

**Comment by CyberZHG** [comment]
Because it is transposed in the official implementation:

https://github.com/google-research/bert/blob/88a817c37f788702a363ff935fd173b6dc6ac0d6/run_pretraining.py#L298

MLM also transposes the weights:

https://github.com/CyberZHG/keras-bert/blob/b8fa69072618b2fa3b8912ae78e675ac9531128f/keras_bert/layers/embedding.py#L110
