### ISSUE TITLE
finetune BERT with custom dataset

### ISSUE THREAD

**Issue by BerenLuthien** [CyberZHG/keras-bert#20]
**Is your feature request related to a problem? Please describe.**
Wish to finetune BERT (MLM, PairSentence) with customer dataset, e.g. text exacted from a book.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Which function wherein we can feed a customer dataset, for example, a text file from a book ?
Do we need write a function to format the text file so that it can be taken by BERT ?

**Additional context**

**Comment by CyberZHG** [comment]
There is a test case that trains the model:

https://github.com/CyberZHG/keras-bert/blob/02c7eb20c56b02ed74226d056354658c247ab52c/tests/test_bert.py#L26-L93

However, I recommend training with the official implementation then load the checkpoint (since the optimizer and the creation of sentence pairs are different).
