### ISSUE TITLE
OOV (out of vocab)

### ISSUE THREAD

**Issue by BerenLuthien** [CyberZHG/keras-bert#22]
**Is your feature request related to a problem? Please describe.**
Some words are out of the vocab.txt (which is from https://github.com/google-research/bert and gives 30522 words), e.g., "**edits**" is OOV.

**Describe the solution you'd like**
I am thinking random initialize a 512 embedding for the OOV words, but not sure it works, and how.
Besides, since OOV is a very common problem, maybe there is already some **off-the-shelf solution code for keras-BERT** ?  
Many thanks
**Describe alternatives you've considered**
NA

**Additional context**

**Comment by CyberZHG** [comment]
You should use the tokenizer in the official repo since it cuts the unknown words into small fragments that exist in the vocabulary. 

Use the mean and variance of existing embeddings as the parameters of the random normal distribution to initialize the embedding of OOV words if you want to use pre-trained word embeddings. Otherwise, just use some random values.

**Comment by BerenLuthien** [comment]
Thanks a lot for prompt response. Quick follow up to avoid miscommunication :
By "official repo" , do you mean the Google BERT https://github.com/google-research/bert ?

Thanks

**Comment by CyberZHG** [comment]
https://github.com/google-research/bert/blob/master/tokenization.py#L161
